import React, { useState } from "react";

import Roz from "../components/Charts/BarChart";

// import data from "../data";
function Roz_test() {
  const data = [
    {
      role: "",
      client_id: "cad99cb3-f214-4f17-9d6a-31b9910e8e80",
      consent_form: false,
      age: "25-29",
      gender: "t-female",
      preferred_writing_language: "as",
      preferred_reading_language: "ae",
      country: "AU",
      nationality: "Bahamas",
      ethnicity: "indian",
      text_directionality: "left-to-right",
      internet_stability: "Yes",
      broadband_contract: "No",
      age_first_used_technology: 46,
      competency_level: "Intermediate",
      age_when_first_owned_device: 43,
      device_ownership_status: "1-3",
      device_sharing_status: "No",
      device_type_owned: "Computer",
      device_access: "Computer",
      design_principles: {
        principle1: 1,
        principle2: 2,
        principle3: 2,
        principle4: 1,
        principle5: 2,
        principle6: 3,
        principle7: 1,
      },
      time_personal_home_life: "",
      good_performance: "",
      employment: "",
      pleasant_people: "",
      work_interesting: "",
      consulted_by_superiors: "",
      desirable_area: "",
      respected_by_family: "",
      chances_for_promotion: "",
      keeping_time_for_fun: "",
      moderation: "",
      service_to_friend: "",
      thrift: "",
      nervous_tense: "",
      happiness: "",
      prevention_due_to_circumstances: "",
      state_of_health: "",
      proud_citizen: "",
      contradicting_superior: "",
      good_manager: "",
      persistent_efforts: "",
      organization_structure: "",
      organization_rules: "",
      education: "",
      job: "",
    },
    {
      role: "",
      client_id: "cad99cb3-f214-4f17-9d6a-31b9910e8e80",
      consent_form: false,
      age: "25-29",
      gender: "t-female",
      preferred_writing_language: "as",
      preferred_reading_language: "ae",
      country: "AU",
      nationality: "Bahamas",
      ethnicity: "indian",
      text_directionality: "left-to-right",
      internet_stability: "Yes",
      broadband_contract: "No",
      age_first_used_technology: 46,
      competency_level: "Intermediate",
      age_when_first_owned_device: 43,
      device_ownership_status: "1-3",
      device_sharing_status: "No",
      device_type_owned: "Computer",
      device_access: "Computer",
      design_principles: {
        principle1: 1,
        principle2: 2,
        principle3: 2,
        principle4: 1,
        principle5: 2,
        principle6: 3,
        principle7: 1,
      },
      time_personal_home_life: "",
      good_performance: "",
      employment: "",
      pleasant_people: "",
      work_interesting: "",
      consulted_by_superiors: "",
      desirable_area: "",
      respected_by_family: "",
      chances_for_promotion: "",
      keeping_time_for_fun: "",
      moderation: "",
      service_to_friend: "",
      thrift: "",
      nervous_tense: "",
      happiness: "",
      prevention_due_to_circumstances: "",
      state_of_health: "",
      proud_citizen: "",
      contradicting_superior: "",
      good_manager: "",
      persistent_efforts: "",
      organization_structure: "",
      organization_rules: "",
      education: "",
      job: "",
    },
    {
      role: "",
      client_id: "cad99cb3-f214-4f17-9d6a-31b9910e8e80",
      consent_form: false,
      age: "25-29",
      gender: "t-female",
      preferred_writing_language: "as",
      preferred_reading_language: "ae",
      country: "AU",
      nationality: "Bahamas",
      ethnicity: "indian",
      text_directionality: "left-to-right",
      internet_stability: "Yes",
      broadband_contract: "No",
      age_first_used_technology: 46,
      competency_level: "Novice",
      age_when_first_owned_device: 43,
      device_ownership_status: "1-3",
      device_sharing_status: "No",
      device_type_owned: "Computer",
      device_access: "Computer",
      design_principles: {
        principle1: 1,
        principle2: 2,
        principle3: 2,
        principle4: 1,
        principle5: 2,
        principle6: 3,
        principle7: 1,
      },
      time_personal_home_life: "",
      good_performance: "",
      employment: "",
      pleasant_people: "",
      work_interesting: "",
      consulted_by_superiors: "",
      desirable_area: "",
      respected_by_family: "",
      chances_for_promotion: "",
      keeping_time_for_fun: "",
      moderation: "",
      service_to_friend: "",
      thrift: "",
      nervous_tense: "",
      happiness: "",
      prevention_due_to_circumstances: "",
      state_of_health: "",
      proud_citizen: "",
      contradicting_superior: "",
      good_manager: "",
      persistent_efforts: "",
      organization_structure: "",
      organization_rules: "",
      education: "",
      job: "",
    },
    {
      role: "",
      client_id: "cad99cb3-f214-4f17-9d6a-31b9910e8e80",
      consent_form: false,
      age: "25-29",
      gender: "t-female",
      preferred_writing_language: "as",
      preferred_reading_language: "ae",
      country: "AU",
      nationality: "Bahamas",
      ethnicity: "indian",
      text_directionality: "left-to-right",
      internet_stability: "Yes",
      broadband_contract: "No",
      age_first_used_technology: 46,
      competency_level: "Expert",
      age_when_first_owned_device: 43,
      device_ownership_status: "1-3",
      device_sharing_status: "No",
      device_type_owned: "Computer",
      device_access: "Computer",
      design_principles: {
        principle1: 1,
        principle2: 2,
        principle3: 2,
        principle4: 1,
        principle5: 2,
        principle6: 3,
        principle7: 1,
      },
      time_personal_home_life: "",
      good_performance: "",
      employment: "",
      pleasant_people: "",
      work_interesting: "",
      consulted_by_superiors: "",
      desirable_area: "",
      respected_by_family: "",
      chances_for_promotion: "",
      keeping_time_for_fun: "",
      moderation: "",
      service_to_friend: "",
      thrift: "",
      nervous_tense: "",
      happiness: "",
      prevention_due_to_circumstances: "",
      state_of_health: "",
      proud_citizen: "",
      contradicting_superior: "",
      good_manager: "",
      persistent_efforts: "",
      organization_structure: "",
      organization_rules: "",
      education: "",
      job: "",
    },
    {
      role: "participant",
      client_id: "0268b37e-a3d4-4ba2-9a6f-dd76c9b34a35",
      consent_form: false,
      age: "25-29",
      gender: "male",
      preferred_writing_language: "ay",
      preferred_reading_language: "eu",
      country: "BB",
      nationality: "Barbados",
      ethnicity: "chinese",
      text_directionality: "right-to-left",
      internet_stability: "Yes",
      broadband_contract: "No",
      age_first_used_technology: 44,
      competency_level: "Novice",
      age_when_first_owned_device: 46,
      device_ownership_status: "1-3",
      device_sharing_status: "Yes",
      device_type_owned: "Computer",
      device_access: "Smartphone",
      design_principles: {
        principle1: 1,
        principle2: 2,
        principle3: 3,
        principle4: 1,
        principle5: 2,
        principle6: 2,
        principle7: 1,
      },
      time_personal_home_life: "",
      good_performance: "",
      employment: "",
      pleasant_people: "",
      work_interesting: "",
      consulted_by_superiors: "",
      desirable_area: "",
      respected_by_family: "",
      chances_for_promotion: "",
      keeping_time_for_fun: "",
      moderation: "",
      service_to_friend: "",
      thrift: "",
      nervous_tense: "",
      happiness: "",
      prevention_due_to_circumstances: "",
      state_of_health: "",
      proud_citizen: "",
      contradicting_superior: "",
      good_manager: "",
      persistent_efforts: "",
      organization_structure: "",
      organization_rules: "",
      education: "",
      job: "",
    },
    {
      role: "participant",
      client_id: "545e067d-3f7f-4fef-b956-6494827a4319",
      consent_form: true,
      age: "18-19",
      gender: "female",
      preferred_writing_language: "az",
      preferred_reading_language: "ba",
      country: "BH",
      nationality: "Belarus",
      ethnicity: "mixed-asian",
      text_directionality: "left-to-right",
      internet_stability: "Yes",
      broadband_contract: "No",
      age_first_used_technology: 44,
      competency_level: "Intermediate",
      age_when_first_owned_device: 45,
      device_ownership_status: "1-3",
      device_sharing_status: "No",
      device_type_owned: "Computer",
      device_access: "Computer",
      design_principles: {
        principle1: 1,
        principle2: 2,
        principle3: 2,
        principle4: 1,
        principle5: 3,
        principle6: 4,
        principle7: 2,
      },
      time_personal_home_life: "",
      good_performance: "",
      employment: "",
      pleasant_people: "",
      work_interesting: "",
      consulted_by_superiors: "",
      desirable_area: "",
      respected_by_family: "",
      chances_for_promotion: "",
      keeping_time_for_fun: "",
      moderation: "",
      service_to_friend: "",
      thrift: "",
      nervous_tense: "",
      happiness: "",
      prevention_due_to_circumstances: "",
      state_of_health: "",
      proud_citizen: "",
      contradicting_superior: "",
      good_manager: "",
      persistent_efforts: "",
      organization_structure: "",
      organization_rules: "",
      education: "",
      job: "",
    },
  ];

  const competencyByCountry = {};

  for (const participant of data) {
    const competencyLevel = participant.competency_level;
    const country = participant.country;

    if (!competencyByCountry[country]) {
      competencyByCountry[country] = {
        Novice: 0,
        Intermediate: 0,
        Expert: 0,
      };
    }

    competencyByCountry[country][competencyLevel]++;
  }

  const [userData, setUserData] = useState({
    labels: Object.keys(competencyByCountry),
    datasets: [
      {
        label: "Novice",
        backgroundColor: "rgba(255, 99, 132, 0.2)",
        borderColor: "rgba(255, 99, 132, 1)",
        borderWidth: 1,
        data: Object.keys(competencyByCountry).map(
          (country) => competencyByCountry[country].Novice
        ),
      },
      {
        label: "Intermediate",
        backgroundColor: "rgba(54, 162, 235, 0.2)",
        borderColor: "rgba(54, 162, 235, 1)",
        borderWidth: 1,
        data: Object.keys(competencyByCountry).map(
          (country) => competencyByCountry[country].Intermediate
        ),
      },
      {
        label: "Expert",
        backgroundColor: "rgba(255, 206, 86, 0.2)",
        borderColor: "rgba(255, 206, 86, 1)",
        borderWidth: 1,
        data: Object.keys(competencyByCountry).map(
          (country) => competencyByCountry[country].Expert
        ),
      },
    ],
  });

  return (
    <div>
      <Roz chartData={userData}></Roz>
      <div>Hello</div>
    </div>
  );
}

export default Roz_test;
// import React, { useState } from "react";
// import styles from "../style";
// import { Navbar, Hero } from "../components/GetStartedPage";
// import Roz from "../components/Charts/BarChart";
// // import data from "../data";
// function Roz_test() {
//   const [userData, setUserData] = useState({
//     labels: ["", "", ""],
//     datasets: [
//       {
//         label: "Novice",
//         backgroundColor: "blue",
//         data: [30, 20, 50],
//       },
//       {
//         label: "Intermidiate",
//         backgroundColor: "red",
//         data: [40, 40, 20],
//       },
//       {
//         label: "Expert",
//         backgroundColor: "green",
//         data: [5, 62, 33],
//       },
//     ],
//   });

//   return (
//     <div className="bg-primary w-full overflow-hidden">
//       <Roz chartData={userData}></Roz>
//       <div>Hello</div>
//     </div>
//   );
// }

// export default Roz_test;
